"""
Visualizador de pares minerados.
Lê os .jsonl de data/raw/ e gera data/report.html com diff lado a lado.

Uso:
    python -m extracao.execucao.visualizacao
    python -m extracao.execucao.visualizacao --smell long_method --limit 20
"""

import argparse
import difflib
import json
import webbrowser
from pathlib import Path

# ── HTML template ────────────────────────────────────────────────────────────

HTML_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Mined Pairs — {smell}</title>
<style>
  :root {{
    --bg: #1e1e1e; --surface: #252526; --border: #3c3c3c;
    --add: #1e4620; --add-hl: #2ea043; --add-num: #163b18;
    --del: #4b1113; --del-hl: #f85149; --del-num: #3d0e10;
    --eq: #252526; --eq-num: #1e1e1e;
    --txt: #cccccc; --muted: #858585; --accent: #569cd6;
    --tag-bg: #0d2137; --tag-txt: #4fc1ff;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          background: var(--bg); color: var(--txt); font-size: 14px; }}
  header {{ padding: 20px 28px; border-bottom: 1px solid var(--border);
            display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }}
  header h1 {{ font-size: 1.1rem; font-weight: 600; color: var(--accent); }}
  .meta {{ font-size: 0.82rem; color: var(--muted); }}
  .controls {{ margin-left: auto; display: flex; gap: 10px; flex-wrap: wrap; }}
  .controls label {{ font-size: 0.82rem; color: var(--muted); display: flex;
                     align-items: center; gap: 6px; cursor: pointer; }}
  .pair {{ margin: 24px 28px; border: 1px solid var(--border); border-radius: 6px;
           overflow: hidden; }}
  .pair-header {{ background: var(--surface); padding: 10px 16px;
                  display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
                  border-bottom: 1px solid var(--border); }}
  .pair-header .idx {{ color: var(--muted); font-size: 0.8rem; min-width: 32px; }}
  .pair-header .fname {{ font-weight: 600; font-family: monospace; color: var(--accent); }}
  .pair-header .repo {{ font-size: 0.78rem; color: var(--muted); margin-left: auto; }}
  .tag {{ display: inline-block; padding: 1px 8px; border-radius: 3px; font-size: 0.75rem;
          font-weight: 600; background: var(--tag-bg); color: var(--tag-txt); }}
  .diff-wrap {{ overflow-x: auto; }}
  table.diff {{ width: 100%; border-collapse: collapse; font-family: "SF Mono", Menlo,
                Consolas, monospace; font-size: 0.82rem; line-height: 1.55; }}
  table.diff td {{ padding: 1px 12px; white-space: pre; vertical-align: top; }}
  td.num {{ width: 1%; min-width: 36px; text-align: right; padding: 1px 8px;
            user-select: none; color: var(--muted); border-right: 1px solid var(--border); }}
  td.num.add {{ background: var(--add-num); color: var(--add-hl); }}
  td.num.del {{ background: var(--del-num); color: var(--del-hl); }}
  td.num.eq  {{ background: var(--eq-num); }}
  td.code.add {{ background: var(--add); }}
  td.code.del {{ background: var(--del); }}
  td.code.eq  {{ background: var(--eq); }}
  .sign {{ min-width: 14px; display: inline-block; }}
  .hidden {{ display: none; }}
  .summary {{ padding: 24px 28px; color: var(--muted); font-size: 0.88rem;
              border-top: 1px solid var(--border); margin-top: 8px; }}
</style>
</head>
<body>
<header>
  <h1>Mined Pairs — <span style="color:#ce9178">{smell}</span></h1>
  <span class="meta">{count} pairs · {repos} repos</span>
  <div class="controls">
    <label><input type="checkbox" id="hide-eq" onchange="toggleEq(this)"> Hide unchanged lines</label>
  </div>
</header>
"""

HTML_FOOT = """
<div class="summary">Generated by smells/mining/visualize.py</div>
<script>
function toggleEq(cb) {{
  document.querySelectorAll('tr.eq-row').forEach(r => {{
    r.classList.toggle('hidden', cb.checked);
  }});
}}
</script>
</body></html>
"""

# ── Diff builder ─────────────────────────────────────────────────────────────

def build_diff_table(before: str, after: str) -> str:
    before_lines = before.splitlines()
    after_lines  = after.splitlines()

    matcher = difflib.SequenceMatcher(None, before_lines, after_lines, autojunk=False)
    rows = []

    b_num = a_num = 0
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            for k in range(i2 - i1):
                b_num += 1; a_num += 1
                line = _esc(before_lines[i1 + k])
                rows.append(
                    f'<tr class="eq-row">'
                    f'<td class="num eq">{b_num}</td><td class="code eq"><span class="sign"> </span>{line}</td>'
                    f'<td class="num eq">{a_num}</td><td class="code eq"><span class="sign"> </span>{line}</td>'
                    f'</tr>'
                )
        elif tag in ("replace", "delete", "insert"):
            del_lines = before_lines[i1:i2]
            ins_lines = after_lines[j1:j2]
            max_len = max(len(del_lines), len(ins_lines))
            for k in range(max_len):
                del_cell = ins_cell = ""
                del_num_cell = ins_num_cell = ""
                if k < len(del_lines):
                    b_num += 1
                    del_num_cell = f'<td class="num del">{b_num}</td>'
                    del_cell     = f'<td class="code del"><span class="sign">−</span>{_esc(del_lines[k])}</td>'
                else:
                    del_num_cell = '<td class="num eq"></td>'
                    del_cell     = '<td class="code eq"></td>'
                if k < len(ins_lines):
                    a_num += 1
                    ins_num_cell = f'<td class="num add">{a_num}</td>'
                    ins_cell     = f'<td class="code add"><span class="sign">+</span>{_esc(ins_lines[k])}</td>'
                else:
                    ins_num_cell = '<td class="num eq"></td>'
                    ins_cell     = '<td class="code eq"></td>'
                rows.append(f'<tr>{del_num_cell}{del_cell}{ins_num_cell}{ins_cell}</tr>')

    return '<div class="diff-wrap"><table class="diff">' + "".join(rows) + "</table></div>"

def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

# ── Main ─────────────────────────────────────────────────────────────────────

def load_pairs(data_dir: Path, smell: str, limit: int) -> list[dict]:
    path = data_dir / f"{smell}.jsonl"
    if not path.exists():
        raise FileNotFoundError(f"Not found: {path}")
    pairs = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                pairs.append(json.loads(line))
            if len(pairs) >= limit:
                break
    return pairs

def render(pairs: list[dict], smell: str, out_path: Path):
    repos = len({p.get("repo", "") for p in pairs})
    html = [HTML_HEAD.format(smell=smell, count=len(pairs), repos=repos)]

    for i, p in enumerate(pairs, 1):
        # Campos do schema unificado core.schema.RefactoringPair.
        repo_short = (p.get("repo") or "").replace("https://github.com/", "")
        commit_short = (p.get("commit_hash") or "")[:7]
        verified = "verified" if p.get("verified") else "nao-verificado"
        html.append(f"""
<div class="pair">
  <div class="pair-header">
    <span class="idx">#{i}</span>
    <span class="fname">{_esc(p.get("function_name") or "?")}</span>
    <span class="tag">{p.get("smell_type", "?")}</span>
    <span class="repo">{_esc(repo_short)} · {_esc(p.get("file") or "")} · <code>{commit_short}</code> · {verified}</span>
  </div>
  {build_diff_table(p.get("before_code", ""), p.get("after_code", ""))}
</div>""")

    html.append(HTML_FOOT)
    out_path.write_text("".join(html), encoding="utf-8")
    print(f"Report: {out_path.resolve()}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--smell",   default=None, help="Filter by smell (default: all)")
    ap.add_argument("--limit",   type=int, default=50, help="Max pairs per smell (default: 50)")
    ap.add_argument("--data",    default="data/raw", help="Directory with .jsonl files")
    ap.add_argument("--out",     default="data/report.html")
    ap.add_argument("--no-open", action="store_true", help="Don't open browser automatically")
    args = ap.parse_args()

    data_dir = Path(args.data)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    smells = (
        [args.smell] if args.smell
        else [p.stem for p in data_dir.glob("*.jsonl")]
    )

    if not smells:
        print(f"No .jsonl files found in {data_dir}")
        return

    all_pairs = []
    for smell in smells:
        try:
            all_pairs.extend(load_pairs(data_dir, smell, args.limit))
        except FileNotFoundError as e:
            print(f"Warning: {e}")

    if not all_pairs:
        print("No pairs to render.")
        return

    label = args.smell or "all smells"
    render(all_pairs, label, out_path)

    if not args.no_open:
        webbrowser.open(out_path.resolve().as_uri())

if __name__ == "__main__":
    main()